name: w2vpos
dependencies:
  - python=3.6.*
  - pip=19.3.*
  - gensim=3.8.*
  - matplotlib=3.*
  - nltk=3.4.*
  - numpy=1.16.*
  - pandas=0.24.*
  - scikit-learn=0.22.*
  - tqdm=4.44.*
  - pip:
    - spacy==1.10.*
    - tabulate==0.8.*
