name: w2vpos
dependencies:
  - python=3.6.*
  - pip=19.3.*
  - gensim=3.8.0
  - matplotlib=3.1.3
  - nltk=3.4.5
  - numpy=1.16.6
  - pandas=1.0.3
  - tqdm=4.44.1
  - pip:
      - pandarallel==1.4.8
      - scikit-learn==0.17.1
      - scipy==1.2.3
      - spacy==1.10.1
      - tabulate==0.8.7
